---
- name: add grafana repo
  copy:
      dest: /etc/yum.repos.d/grafana.repo
      src: files/grafana.repo
- name: install grafana package
  yum:
    name: grafana
    state: present
  notify: restart grafana
...
