-
  name: 'start task1_host1'
  hosts: host1
  become: true
  gather_facts: false
  roles:
    - 'task1_host1'
-
  name: 'start task1_host2'
  hosts: host2
  become: true
  gather_facts: false
  roles:
    - 'task1_host2'
-
  name: 'start task1_host3'
  hosts: host3
  become: true
  gather_facts: false
  roles:
    - 'task1_host3'
