-
  name: commands
  shell: |
    modprobe bonding
    nmcli connection add type bond con-name "bond1" ifname bond0 mode balance-rr
    nmcli connection modify "bond1" ipv4.addresses "192.168.255.1/30" ipv4.method manual
    for device in eth1 eth2; do
        nmcli connection add type bond-slave con-name "bond1-$device" ifname "$device" master bond0
    done
    nmcli connection up "bond1"
    iptables -t nat -A POSTROUTING ! -d 192.168.0.0/16 -o eth0 -j MASQUERADE
    echo 'net.ipv4.ip_forward = 1' >> /etc/sysctl.conf
    sysctl -p /etc/sysctl.conf
    nmcli connection modify "bond1" +ipv4.routes "192.168.0.0/16 192.168.255.2"
    nmcli connection up "bond1"
  