---
- name: download sources
  get_url:
    dest: /tmp/prometheus.tar.gz
    url: https://github.com/prometheus/prometheus/releases/download/v{{ prometheus_version }}/prometheus-{{ prometheus_version }}.linux-amd64.tar.gz
  notify: restart prometheus

- set_fact:
    src_path: /tmp/prometheus-{{ prometheus_version }}.linux-amd64

- name: unarchive sources
  unarchive:
    src: /tmp/prometheus.tar.gz
    dest: /tmp
    remote_src: yes
    creates: "{{ src_path }}"
  notify: restart prometheus

- name: Copy exec file to /usr/bin
  copy:
    dest: /usr/bin/prometheus
    src: "{{ src_path }}/prometheus"
    remote_src: yes
    mode: 755
  notify: restart prometheus

- name: Copy systemd-service unit file
  copy:
    dest: /etc/systemd/system/prometheus.service
    src: files/prometheus.service
  notify: restart prometheus

- name: Copy config file
  template:
    dest: /etc/prometheus.yml
    src: templates/prometheus.yml
  notify: restart prometheus
